module.exports = {
    PendingVerification: 2 << 0,
    Default: 2 << 1,
    Supporter: 2 << 2,
    BAT: 2 << 3,
    TournamentStaff: 2 << 4,
    AdminPannelAccess: 2 << 5,
    AdminManageUsers: 2 << 6,
    AdminBanUsers: 2 << 7,
    AdminSilenceUsers: 2 << 8,
    AdminWipeUsers: 2 << 9,
    AdminBeatmaps: 2 << 10,
    AdminDeveloper: 2 << 11,
    AdminSettings: 2 << 12,
    AdminReports: 2 << 13,
    AdminPrivileges: 2 << 14,
    AdminSendAlerts: 2 << 15,
    AdminChatMod: 2 << 16,
    AdminKickUsers: 2 << 17,
};